### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by andku83**

### CODE REVIEW

**Comment by zxbodya** [comment]
I think `jpeg_quality` is correct option:
http://imagine.readthedocs.io/en/latest/usage/introduction.html#save-images

**Comment by andku83** [comment]
You are required "yiisoft/yii2-imagine": "*"
in https://github.com/yiisoft/yii2-imagine#usage--documentation
      ->save('path/to/destination/image.jpg', ['quality' => 50]);
and yiisoft/yii2-imagine required not latest version Imagine

You work  "jpeg_quality" ?
For me works "quality".

**Comment by zxbodya** [comment]
Checked Imagine code - `quality` is deprecated

https://github.com/avalanche123/Imagine/blob/68d416ee2be3423c5758bddd31be11fcd80d16e5/CHANGELOG.md#060-2014-06-13

and effectively is the same as `jpeg_quality` in this particular case: 

https://github.com/avalanche123/Imagine/blob/68d416ee2be3423c5758bddd31be11fcd80d16e5/lib/Imagine/Image/AbstractImage.php#L95

**Comment by andku83** [comment]
теперь когда yiisoft/yii2-imagine обновились этот параметр соответствует ))

**Pull request closed without merging**
